<?php
/**
 * nba_name_map.php — NBA Player Name Normalization + Alias Map
 *
 * Provides:
 *   normalizeName($name)  → canonical lowercase key for all lookups
 *   $NAME_ALIASES[]       → maps sportsbook spellings → BDL canonical names
 *
 * Usage: require_once 'nba_name_map.php';
 */

function normalizeName($name) {
    if (!$name) return '';
    $name = strtolower(trim($name));
    $name = str_replace(['.', "'", '-', ','], ['', '', ' ', ''], $name);
    $name = preg_replace('/\s+(jr|sr|iii|ii|iv)\s*$/i', '', $name);
    return preg_replace('/\s+/', ' ', trim($name));
}

/**
 * Maps sportsbook display names → BDL canonical names (normalized).
 * Keys and values are both already normalized (run through normalizeName()).
 *
 * Add entries whenever a mismatch is discovered in production.
 * Format: 'sportsbook spelling' => 'bdl canonical'
 */
$NAME_ALIASES = [
    // Common abbreviation vs full name mismatches
    'og anunoby'                  => 'og anunoby',
    'alexandre sarr'              => 'alex sarr',
    'cam thomas'                  => 'cameron thomas',
    'cam johnson'                 => 'cameron johnson',
    'cam payne'                   => 'cameron payne',
    'cam whitmore'                => 'cameron whitmore',
    'nahe miles-walker'           => 'nahe miles-walker',
    'nah e miles walker'           => 'nahe miles-walker',
    'trey murphy'                 => 'trey murphy iii',
    'wendell carter'              => 'wendell carter jr',
    'gary trent'                  => 'gary trent jr',
    'gary payton'                 => 'gary payton ii',
    'otto porter'                 => 'otto porter jr',
    'michael porter'              => 'michael porter jr',
    'jaren jackson'               => 'jaren jackson jr',
    'tim hardaway'                => 'tim hardaway jr',
    'larry nance'                 => 'larry nance jr',
    'marvin bagley'               => 'marvin bagley iii',
    'kevin porter'                => 'kevin porter jr',
    'jabari walker'               => 'jabari walker',
    'derrick jones'               => 'derrick jones jr',
    'terence davis'               => 'terence davis ii',
    'gary harris'                 => 'gary harris',
    'nicolas claxton'             => 'nic claxton',
    'nic claxton'                 => 'nic claxton',
    'nicholas claxton'            => 'nic claxton',
    'isaiah hartenstein'          => 'isaiah hartenstein',
    'alexandre sarr'              => 'alex sarr',
    'goga bitadze'                => 'goga bitadze',
    'alperen sengun'              => 'alperen sengun',
    'shai gilgeous-alexander'     => 'shai gilgeous alexander',
    'shai gilgeous alexander'     => 'shai gilgeous alexander',
    'sga'                         => 'shai gilgeous alexander',
    'lebron james'                => 'lebron james',
    'lbj'                         => 'lebron james',
    'steph curry'                 => 'stephen curry',
    'stephen curry'               => 'stephen curry',
    'nikola jokic'                => 'nikola jokic',
    'joker'                       => 'nikola jokic',
    'luka doncic'                 => 'luka doncic',
    'luka dončić'                 => 'luka doncic',
    'giannis antetokounmpo'       => 'giannis antetokounmpo',
    'giannis'                     => 'giannis antetokounmpo',
    'jayson tatum'                => 'jayson tatum',
    'devin booker'                => 'devin booker',
    'anthony edwards'             => 'anthony edwards',
    'ant edwards'                 => 'anthony edwards',
    'ant'                         => 'anthony edwards',
    'victor wembanyama'           => 'victor wembanyama',
    'wemby'                       => 'victor wembanyama',
    'chet holmgren'               => 'chet holmgren',
    'donovan mitchell'            => 'donovan mitchell',
    'spida'                       => 'donovan mitchell',
    'damian lillard'              => 'damian lillard',
    'dame'                        => 'damian lillard',
    'jimmy butler'                => 'jimmy butler',
    'bam adebayo'                 => 'bam adebayo',
    'pascal siakam'               => 'pascal siakam',
    'darius garland'              => 'darius garland',
    'tyrese haliburton'           => 'tyrese haliburton',
    'hali'                        => 'tyrese haliburton',
    'tyrese maxey'                => 'tyrese maxey',
    'kawhi leonard'               => 'kawhi leonard',
    'paul george'                 => 'paul george',
    'pg'                          => 'paul george',
    'trae young'                  => 'trae young',
    'ice trae'                    => 'trae young',
    'zion williamson'             => 'zion williamson',
    'ja morant'                   => 'ja morant',
    'karl-anthony towns'          => 'karl-anthony towns',
    'kat'                         => 'karl-anthony towns',
    'karl anthony towns'          => 'karl-anthony towns',
    'julius randle'               => 'julius randle',
    'RJ barrett'                  => 'rj barrett',
    'rj barrett'                  => 'rj barrett',
    'jalen brunson'               => 'jalen brunson',
    'mikal bridges'               => 'mikal bridges',
    'josh hart'                   => 'josh hart',
    'donte divincenzo'            => 'donte divincenzo',
    'naz reid'                    => 'naz reid',
    'rudy gobert'                 => 'rudy gobert',
    'jaden mcdaniels'             => 'jaden mcdaniels',
    'nikola vucevic'              => 'nikola vucevic',
    'vucevic'                     => 'nikola vucevic',
    'zach lavine'                 => 'zach lavine',
    'coby white'                  => 'coby white',
    'jaylen brown'                => 'jaylen brown',
    'al horford'                  => 'al horford',
    'kristaps porzingis'          => 'kristaps porzingis',
    'kp'                          => 'kristaps porzingis',
    'jrue holiday'                => 'jrue holiday',
    'payton pritchard'            => 'payton pritchard',
    'derrick white'               => 'derrick white',
    'james harden'                => 'james harden',
    'joel embiid'                 => 'joel embiid',
    'tobias harris'               => 'tobias harris',
    'de anthony melton'           => 'de anthony melton',
    'deanthony melton'            => 'de anthony melton',
    'obi toppin'                  => 'obi toppin',
    'andrew nembhard'             => 'andrew nembhard',
    'myles turner'                => 'myles turner',
    'bennedict mathurin'          => 'bennedict mathurin',
    'pascal siakam'               => 'pascal siakam',
    'scottie barnes'              => 'scottie barnes',
    'immanuel quickley'           => 'immanuel quickley',
    'iq'                          => 'immanuel quickley',
    'brandon ingram'              => 'brandon ingram',
    'cj mccollum'                 => 'cj mccollum',
    'herb jones'                  => 'herb jones',
    'dejounte murray'             => 'dejounte murray',
    'jalen johnson'               => 'jalen johnson',
    'dyson daniels'               => 'dyson daniels',
    'de andre hunter'             => 'de andre hunter',
    'deandre hunter'              => 'de andre hunter',
    'clint capela'                => 'clint capela',
    'lauri markkanen'             => 'lauri markkanen',
    'jordan clarkson'             => 'jordan clarkson',
    'collin sexton'               => 'collin sexton',
    'walker kessler'              => 'walker kessler',
    'john collins'                => 'john collins',
    'luguentz dort'               => 'luguentz dort',
    'lu dort'                     => 'luguentz dort',
    'isaiah joe'                  => 'isaiah joe',
    'kenrich williams'            => 'kenrich williams',
    'jalen williams'              => 'jalen williams',
    'josh giddey'                 => 'josh giddey',
    'draymond green'              => 'draymond green',
    'klay thompson'               => 'klay thompson',
    'jonathan kuminga'            => 'jonathan kuminga',
    'brandin podziemski'          => 'brandin podziemski',
    'andrew wiggins'              => 'andrew wiggins',
    'evan mobley'                 => 'evan mobley',
    'max strus'                   => 'max strus',
    'sam merrill'                 => 'sam merrill',
    'caris levert'                => 'caris levert',
    'ty jerome'                   => 'ty jerome',
    'georges niang'               => 'georges niang',
    'dean wade'                   => 'dean wade',
    'jarrett allen'               => 'jarrett allen',
    'cade cunningham'             => 'cade cunningham',
    'jaden ivey'                  => 'jaden ivey',
    'ausar thompson'              => 'ausar thompson',
    'bojan bogdanovic'            => 'bojan bogdanovic',
    'tobias harris'               => 'tobias harris',
    'tim hardaway jr'             => 'tim hardaway jr',
    'monte morris'                => 'monte morris',
    'nba'                         => '',
];
