"""Legacy module aliases so pickles saved before the reorganization still load.

Pickles serialize fully-qualified class paths. Before the repo was
reorganized into src/nba_props_model/, classes lived at flat module paths
like `correlation_engine.WithinPlayerCorrelationEngine`. When those
pickles are opened today, unpickling triggers `import correlation_engine`
which no longer exists, so we register the legacy names in sys.modules
pointing at their new locations.

Remove these shims once every artifact has been regenerated by a retrain
under the new layout.
"""
import sys

_LEGACY_TO_NEW = {
    "bdl_client":             "nba_props_model.data.bdl_client",
    "feature_engineering":    "nba_props_model.features.engineering",
    "retrospective_features": "nba_props_model.features.retrospective",
    "minutes_model":          "nba_props_model.models.minutes",
    "fg3m_hurdle":            "nba_props_model.models.fg3m_hurdle",
    "calibrate_stat_side":    "nba_props_model.calibration.stat_side_platt",
    "residual_centering":     "nba_props_model.calibration.residual_centering",
    "correlation_engine":     "nba_props_model.correlation.sgp_engine",
}


def install() -> None:
    for legacy, new in _LEGACY_TO_NEW.items():
        if legacy in sys.modules:
            continue
        try:
            sys.modules[legacy] = __import__(new, fromlist=["*"])
        except Exception:
            pass
