"""
Run the full-universe diagnostics suite comparing the new PMF path
against the legacy direct-total path on the same walk-forward holdout.

Per docs/MIGRATION.md §3 step 4: writes
artifacts/docs/diagnostics_{today}.md with per-stat metrics.

Metrics per stat and per fold:
  * log score on the realized outcome under the predicted PMF
  * discrete CRPS
  * randomized PIT mean / std / KS distance from Uniform(0,1)
  * line-level Brier averaged over offered lines from opening-snapshot
  * over/under calibration: slope, intercept, ECE
  * logloss lift vs a neutral 0.5 baseline (real de-vigged market
    probabilities are NOT currently joined into the OOF input; when
    market_eval_available=false the lift column is emitted as NaN
    and the report includes an explicit "Market evaluation status"
    section. Wiring real opening-line de-vigged probs requires joining
    data/opening_lines_*.json onto the OOF rows by
    (player_name, game_date, stat, line) — tracked separately.)
  * edge-decile monotonicity where enough graded rows exist
  * bootstrap ROI 95% CI on the selected-bet subset

Comparison baseline: the *legacy* direct-total quantile path reads
the `q{qpct}_{stat}.pkl` artifacts in artifacts/models/. The new path
reads the same validation rows' PMFs generated by
scripts/calibrate_pmf.py's OOF sweep.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import joblib  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from nba_props_model.calibration.pmf_calibration import load_calibrator  # noqa: E402
from nba_props_model.evaluation.diagnostics import (  # noqa: E402
    FoldMetrics, bootstrap_ci,
    brier, calibration_line_fit, devig_pair,
    discrete_crps, ece, edge_decile_monotonicity, log_score,
    pit_ks_distance, randomized_pit, write_report,
)
from nba_props_model.selection.bet_selection import american_to_implied_prob  # noqa: E402
from nba_props_model.paths import DATA_DIR, MODEL_DIR, REPO_ROOT  # noqa: E402
from nba_props_model.models.simulation import DOMAIN_MAX as MAIN_DOMAIN_MAX  # noqa: E402
from nba_props_model.models.sparse_hurdle import DOMAIN_MAX as SPARSE_DOMAIN_MAX  # noqa: E402

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("run_diagnostics")


DOCS_DIR = REPO_ROOT / "artifacts" / "docs"

# Real de-vigged opening-line probabilities are not yet joined into the
# OOF parquet emitted by scripts/calibrate_pmf.py. Until that join is
# wired in (data/opening_lines_*.json -> per-row over/under probs by
# player_name + game_date + stat + line), diagnostics MUST NOT report a
# market-relative lift. We emit NaN for the lift column, set
# market_eval_available=False in the JSON sidecar, and append an
# explicit warning section to the markdown.
# OOF parquet path: real opening-line de-vig is not joined here; event-market
# evaluation is wired separately via scripts/event_market_diagnostics_wiring.py
# when --require-market-eval is set.
MARKET_EVAL_OOF_OPENING_LINES_AVAILABLE = False


# ── legacy PMF construction from quantile ladder ───────────────────────────


LEGACY_QUANTILES = (0.10, 0.20, 0.25, 0.33, 0.40, 0.50, 0.60, 0.67, 0.75, 0.80, 0.90)


def legacy_pmf_from_quantiles(
    stat: str, quantile_predictions: dict[int, float], domain_max: int,
) -> np.ndarray:
    """Approximate the legacy direct-total path's discrete PMF from its
    quantile ladder at the offered tau values. We anchor at (0, 0) and
    (domain_max, 1) and use linear CDF interpolation."""
    if not quantile_predictions:
        # Degenerate: uniform over the support.
        pmf = np.ones(domain_max + 1) / (domain_max + 1)
        return pmf
    sorted_keys = sorted(quantile_predictions.keys())
    xs = [max(0.0, float(quantile_predictions[k])) for k in sorted_keys]
    for i in range(1, len(xs)):
        if xs[i] < xs[i - 1]:
            xs[i] = xs[i - 1]
    ys = [k / 100.0 for k in sorted_keys]
    xs = [0.0] + xs + [float(domain_max) + 1e-6]
    ys = [0.0] + ys + [1.0]
    support = np.arange(domain_max + 1, dtype=float)
    cdf = np.interp(support, xs, ys)
    cdf[-1] = 1.0
    pmf = np.empty_like(cdf)
    pmf[0] = cdf[0]
    pmf[1:] = np.diff(cdf)
    pmf = np.clip(pmf, 0.0, None)
    s = pmf.sum()
    if s > 0:
        pmf = pmf / s
    return pmf


def load_legacy_ladder(stat: str) -> tuple[Optional[list[str]], dict[int, object]]:
    feat_path = MODEL_DIR / f"features_{stat}.pkl"
    if not feat_path.exists():
        return None, {}
    try:
        features = joblib.load(feat_path)
    except Exception:
        return None, {}
    ladder: dict[int, object] = {}
    for q in LEGACY_QUANTILES:
        qpct = int(round(q * 100))
        p = MODEL_DIR / f"q{qpct:02d}_{stat}.pkl"
        if p.exists():
            try:
                ladder[qpct] = joblib.load(p)
            except Exception:
                continue
    return features, ladder


# ── per-stat diagnostic collector ──────────────────────────────────────────


STATS_TO_REPORT = ["pts", "reb", "ast", "tov", "stl", "blk", "fg3m", "stocks"]

DOMAIN_FOR_STAT = {
    **{s: MAIN_DOMAIN_MAX[s] for s in ("pts", "reb", "ast", "tov")},
    **{s: SPARSE_DOMAIN_MAX[s] for s in ("stl", "blk")},
    "stocks": SPARSE_DOMAIN_MAX["stl"] + SPARSE_DOMAIN_MAX["blk"],
    "fg3m": 15,
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--oof-path", default=str(DATA_DIR / "oof_pmfs.parquet"),
        help="Path to the OOF PMF parquet produced by calibrate_pmf.",
    )
    parser.add_argument("--run-date", default=datetime.utcnow().strftime("%Y-%m-%d"))
    parser.add_argument(
        "--core-props-only", action="store_true",
        help=(
            "Restrict diagnostics to core props (PTS, REB, AST, FG3M, TOV). "
            "Skips STL, BLK, STOCKS. CI runtime optimization."
        ),
    )
    parser.add_argument(
        "--require-market-eval",
        action="store_true",
        help="Run M8.6 event-market stack; fail if not scored (PHASE8_MARKET_EVAL_NOT_WIRED_FAIL).",
    )
    parser.add_argument(
        "--allow-baseline-only",
        action="store_true",
        help="Explicitly allow OOF diagnostics without event-market scoring (market_eval_status=baseline_only).",
    )
    parser.add_argument("--date", default=None, help="Single-date alias (not yet used for OOF slice).")
    parser.add_argument("--start-date", default=None)
    parser.add_argument("--end-date", default=None)
    parser.add_argument("--dates-file", default=None, help="Inventory CSV for event-market stack.")
    parser.add_argument(
        "--snapshot-substr", default="close_or_lock",
        help="Odds pairs filename filter for event-market scripts.",
    )
    parser.add_argument(
        "--allow-provisional-block",
        action="store_true",
        help="Pass through to market superiority verifier after strict check.",
    )
    parser.add_argument(
        "--training-table",
        default=str(DATA_DIR / "training_table.parquet"),
        help="Path to training_table.parquet (legacy ladder join). Default: data/training_table.parquet",
    )
    args = parser.parse_args()
    if args.require_market_eval and args.allow_baseline_only:
        parser.error("--require-market-eval and --allow-baseline-only are mutually exclusive")
    modes = sum(bool(x) for x in (args.date, (args.start_date and args.end_date), args.dates_file))
    if modes > 1:
        parser.error("use only one of --date, --start-date/--end-date, --dates-file for event-market")
    if args.require_market_eval and modes == 0 and not (args.start_date and args.end_date):
        parser.error("--require-market-eval needs --dates-file or --start-date and --end-date")
    core_only_allowed = {"pts", "reb", "ast", "fg3m", "tov"} if args.core_props_only else None

    start = time.time()
    logger.info("=" * 60)
    logger.info("Diagnostics — legacy direct-total vs new PMF path")
    logger.info("=" * 60)

    training_table_path = Path(args.training_table)
    if not training_table_path.exists():
        DOCS_DIR.mkdir(parents=True, exist_ok=True)
        sidecar = DOCS_DIR / f"diagnostics_{args.run_date}.meta.json"
        miss = {
            "diagnostics_status": "failed_preflight",
            "failure_code": "MISSING_TRAINING_TABLE",
            "missing_path": str(training_table_path.resolve()),
            "market_eval_status": "not_run_missing_training_table",
            "market_superiority_claim_allowed": False,
            "global_market_superiority_claim_allowed": False,
            "eligible_market_subset_superiority_claim_allowed": False,
            "model_only_calibration_claim_allowed": False,
            "require_market_eval": bool(args.require_market_eval),
            "allow_baseline_only": bool(args.allow_baseline_only),
            "strict_contract_result": "not_run",
            "promotion_status": "no_market_superiority_claim",
        }
        sidecar.write_text(json.dumps(miss, indent=2) + "\n", encoding="utf-8")
        logger.error(
            "MISSING_TRAINING_TABLE at %s — wrote %s (exit 3)",
            training_table_path,
            sidecar,
        )
        sys.exit(3)

    oof_path = Path(args.oof_path)
    if not oof_path.exists():
        logger.error(
            f"No OOF file at {oof_path}. Run scripts/calibrate_pmf.py "
            "with --emit-oof (or the default behavior that writes it) first."
        )
        sys.exit(1)

    stats_df = pd.read_parquet(DATA_DIR / "player_game_stats.parquet")
    training_df = pd.read_parquet(training_table_path)
    training_df["game_date"] = training_df["game_date"].astype(str).str[:10]

    oof = pd.read_parquet(oof_path)
    oof["game_date"] = oof["game_date"].astype(str).str[:10]

    fold_metrics: list[FoldMetrics] = []
    new_rows: list[dict] = []
    legacy_rows: list[dict] = []
    role_diag_rows: list[dict] = []

    rng = np.random.default_rng(0)
    for stat in sorted(oof["stat"].unique()):
        if core_only_allowed is not None and stat not in core_only_allowed:
            logger.info(f"  {stat}: skipped (--core-props-only)")
            continue
        sub = oof[oof["stat"] == stat].copy()
        sub = sub.sort_values("game_date")
        if len(sub) < 80:
            logger.warning(f"  {stat}: only {len(sub)} OOF rows — skipping diagnostics")
            continue
        domain_max = DOMAIN_FOR_STAT.get(stat, sub["pmf"].iloc[0].shape[0] - 1)

        # Prefer the active-conditioned PMF column when the OOF
        # parquet carries it. Calibrators are fit on `pmf_active`,
        # so diagnostics measured against `pmf_active` align with
        # the training target. Fall back to raw `pmf` for older OOF
        # parquets that pre-date the active-conditioning patch.
        if "pmf_active" in sub.columns:
            new_pmfs = np.stack(sub["pmf_active"].values)
            _diag_pmf_source = "pmf_active"
        else:
            new_pmfs = np.stack(sub["pmf"].values)
            _diag_pmf_source = "pmf"
        logger.info(f"  {stat}: PMF source column = {_diag_pmf_source}")
        new_pmfs = _pad_or_truncate_pmf(new_pmfs, domain_max + 1)
        outcomes = sub["outcome"].values.astype(int)

        # Calibrator is per-stat — load once, not per fold. Role-aware
        # bundles need the ex-ante role_bucket per row; fail loudly if
        # absent rather than silently fall back to the global calibrator.
        cal = load_calibrator(stat)
        if cal is None:
            new_pmfs_cal = new_pmfs
        elif getattr(cal, "version", None) == "role_aware_pmf_cal_v1":
            if "role_bucket" not in sub.columns:
                logger.error(
                    f"role-aware calibrator loaded for {stat} but OOF "
                    "parquet lacks `role_bucket` column. Cannot evaluate "
                    "role-aware calibration without per-row role bucket "
                    "assignments. Regenerate the OOF artifact with "
                    "Stage-3+ calibrate_pmf.py."
                )
                sys.exit(1)
            role_buckets_full = sub["role_bucket"].astype(str).to_numpy()
            new_pmfs_cal = np.stack([
                cal.apply(p, role_bucket=rb)
                for p, rb in zip(new_pmfs, role_buckets_full)
            ])
        else:
            new_pmfs_cal = np.stack([cal.apply(p) for p in new_pmfs])

        # Evaluate new PMF diagnostics fold by fold.
        sub["fold"] = sub["fold_start"].astype(str)
        for fstart in sorted(sub["fold"].unique()):
            chunk = sub[sub["fold"] == fstart]
            if len(chunk) < 50:
                continue
            idx = chunk.index
            sub_idx = [sub.index.get_loc(i) for i in idx]
            pmf_slice = new_pmfs[sub_idx]
            out_slice = outcomes[sub_idx]

            pmf_slice_cal = new_pmfs_cal[sub_idx]

            # Over-prob model: prob(stat > nearest integer line) at a reference
            # line equal to the per-fold median integer for this stat.
            ref_line = float(np.median(out_slice)) + 0.5
            over_probs = 1.0 - _cdf_at(pmf_slice_cal, ref_line)
            over_realised = (out_slice > ref_line).astype(int)

            # Real de-vigged opening-line market probabilities are not
            # joined into the OOF parquet today. Pass NaN so
            # _fold_metrics_from emits market_logscore_lift = NaN
            # instead of a misleading constant-0.5 baseline lift.
            # The appended "Market evaluation status" section makes
            # this gap explicit in the diagnostics markdown.
            market_probs = np.full(len(over_realised), np.nan)

            fm_new = _fold_metrics_from(
                pmf_slice_cal, out_slice, over_probs, market_probs,
                over_realised, stat=f"{stat}__new",
                fold_start=str(chunk["fold_start"].iloc[0]),
                fold_end=str(chunk["fold_end"].iloc[0]),
                rng=rng,
            )
            fold_metrics.append(fm_new)

            # Now the legacy direct-total path on the same rows.
            legacy_features, legacy_ladder = load_legacy_ladder(stat if stat != "tov" else "tov")
            if legacy_features and legacy_ladder:
                legacy_pmfs = _build_legacy_pmfs_for_rows(
                    stat, chunk, training_df, legacy_features, legacy_ladder,
                    domain_max=domain_max,
                )
                if legacy_pmfs is not None and len(legacy_pmfs) == len(out_slice):
                    over_probs_legacy = 1.0 - _cdf_at(legacy_pmfs, ref_line)
                    fm_legacy = _fold_metrics_from(
                        legacy_pmfs, out_slice, over_probs_legacy,
                        market_probs, over_realised, stat=f"{stat}__legacy",
                        fold_start=str(chunk["fold_start"].iloc[0]),
                        fold_end=str(chunk["fold_end"].iloc[0]),
                        rng=rng,
                    )
                    fold_metrics.append(fm_legacy)
                    legacy_rows.extend(
                        [{"stat": stat, "pmf": p, "outcome": y, "fold_start": chunk["fold_start"].iloc[0]}
                         for p, y in zip(legacy_pmfs, out_slice)]
                    )
            new_rows.extend(
                [{"stat": stat, "pmf": p, "outcome": y, "fold_start": chunk["fold_start"].iloc[0]}
                 for p, y in zip(pmf_slice_cal, out_slice)]
            )

        # ── Role-stratified diagnostics (Stage 5 verification) ──────────
        # Only fires when the OOF parquet carries per-row role buckets
        # (post-Stage-3 artifacts). Computed on `new_pmfs_cal`, so for
        # role-aware calibrators these metrics measure the actual blended
        # role × global calibration, not the global isotonic alone.
        #
        # The randomized PIT inside each bucket is seeded deterministically
        # from (stat, role_bucket) via SHA-256 so results are reproducible
        # across processes (Python hash randomization is per-process and
        # would make plain hash() non-reproducible) and independent of
        # the evaluation order of the outer groupby loop.
        if "role_bucket" in sub.columns:
            for role_bucket_label, role_chunk in sub.groupby("role_bucket"):
                if len(role_chunk) < 50:
                    continue
                role_idx = role_chunk.index
                sub_idx_role = [sub.index.get_loc(i) for i in role_idx]
                role_pmf = new_pmfs_cal[sub_idx_role]
                role_out = outcomes[sub_idx_role]
                seed_bytes = hashlib.sha256(
                    f"{stat}|{role_bucket_label}|role_diag".encode("utf-8")
                ).digest()[:8]
                seed = int.from_bytes(seed_bytes, "little") % (2**32)
                role_rng = np.random.default_rng(seed)
                pit = randomized_pit(role_pmf, role_out, role_rng)
                ks = pit_ks_distance(pit)
                ls = log_score(role_pmf, role_out)
                crps = discrete_crps(role_pmf, role_out)
                ref_line_role = float(np.median(role_out)) + 0.5
                over_probs_role = 1.0 - _cdf_at(role_pmf, ref_line_role)
                over_realised_role = (role_out > ref_line_role).astype(int)
                ece_role = float(ece(over_probs_role, over_realised_role))
                role_diag_rows.append({
                    "stat": stat,
                    "role_bucket": str(role_bucket_label),
                    "n": int(len(role_out)),
                    "log_score": float(ls),
                    "crps": float(crps),
                    "pit_mean": float(np.mean(pit)),
                    "pit_std": float(np.std(pit)),
                    "pit_ks": float(ks),
                    "ece": ece_role,
                })

    report_path = DOCS_DIR / f"diagnostics_{args.run_date}.md"
    write_report(fold_metrics, run_date=args.run_date)
    # Append cross-path comparison summary.
    _append_comparison_summary(report_path, fold_metrics, args.run_date)
    # Append role-stratified PMF diagnostics if the OOF carried role buckets.
    _append_role_stratified_section(report_path, role_diag_rows)
    # Append market evaluation status — explicit, never silent.
    _append_market_eval_status(report_path, available=MARKET_EVAL_OOF_OPENING_LINES_AVAILABLE)

    from collections import Counter

    cal_const_folds = [m for m in fold_metrics if m.cal_slope_status == "constant_probs"]
    n_constant_prob_groups = len(cal_const_folds)
    cstat = Counter()
    crole = Counter()
    largest_constant_prob_group_n = 0
    for m in cal_const_folds:
        base = str(m.stat).split("__")[0]
        cstat[base] += 1
        if m.constant_prob_n:
            largest_constant_prob_group_n = max(largest_constant_prob_group_n, m.constant_prob_n)
        mask = (oof["stat"].astype(str) == base) & (oof["fold_start"].astype(str) == str(m.fold_start))
        if "role_bucket" in oof.columns and bool(mask.any()):
            mode_rb = str(oof.loc[mask, "role_bucket"].astype(str).value_counts().idxmax())
            crole[mode_rb] += 1
        else:
            crole["unknown"] += 1
    constant_prob_groups_by_stat = dict(cstat)
    constant_prob_groups_by_role = dict(crole)

    em_payload: dict = {
        "market_eval_status": "baseline_only",
        "event_market_eval_ran": False,
        "strict_contract_result": "not_run",
        "market_superiority_claim_allowed": False,
        "promotion_status": "no_market_superiority_claim",
        "n_event_market_rows": None,
        "n_matched_rows": None,
        "n_scored_rows": None,
        "dates_used": None,
        "required_stats_missing_in_event_rows": None,
        "global_market_superiority_claim_allowed": None,
        "eligible_market_subset_superiority_claim_allowed": None,
        "model_only_calibration_claim_allowed": None,
        "calibration_constant_prob_summary": {
            "n_constant_prob_groups": n_constant_prob_groups,
            "constant_prob_groups_by_stat": constant_prob_groups_by_stat,
            "constant_prob_groups_by_role": constant_prob_groups_by_role,
            "largest_constant_prob_group_n": largest_constant_prob_group_n,
            "constant_prob_fold_keys": [
                f"{m.stat}|{m.fold_start}|{m.fold_end}" for m in cal_const_folds
            ],
        },
    }

    if args.require_market_eval:
        sys.path.insert(0, str(REPO_ROOT / "scripts"))
        import event_market_diagnostics_wiring as emw  # noqa: WPS433

        inv_p: Path | None = Path(args.dates_file) if args.dates_file else None
        if inv_p is None:
            if not (args.start_date and args.end_date):
                logger.error("PHASE8_MARKET_EVAL_NOT_WIRED_FAIL: need --dates-file or --start-date/--end-date")
                sys.exit(2)
            inv_p = emw.ensure_inventory(
                REPO_ROOT,
                sys.executable,
                start_date=args.start_date,
                end_date=args.end_date,
                snapshot_substr=args.snapshot_substr,
            )
        inv_df = pd.read_csv(inv_p)
        if "eligible_for_event_market_backtest" in inv_df.columns:
            ev = inv_df["eligible_for_event_market_backtest"]
            if ev.dtype == object:
                ev = ev.astype(str).str.lower().isin(("1", "true", "t", "yes"))
            n_elig = int((ev == True).sum())  # noqa: E712
        else:
            n_elig = len(inv_df)
        if n_elig == 0:
            logger.error("PHASE8_MARKET_EVAL_NOT_WIRED_FAIL: no eligible_for_event_market_backtest dates")
            em_payload["market_eval_status"] = "blocked_no_eligible_dates"
            em_payload["event_market_eval_ran"] = True
            sys.exit(2)
        stack = emw.run_event_market_stack(
            REPO_ROOT,
            sys.executable,
            dates_file=inv_p,
            snapshot_substr=args.snapshot_substr,
            allow_provisional_block=args.allow_provisional_block,
        )
        em_payload["event_market_eval_ran"] = True
        if not stack.get("ok"):
            logger.error(
                "PHASE8_MARKET_EVAL_NOT_WIRED_FAIL event_market_stack_failed script=%s",
                stack.get("failed_script"),
            )
            sys.exit(2)
        em_payload["n_event_market_rows"] = stack.get("n_event_market_rows")
        em_payload["n_matched_rows"] = stack.get("n_matched_rows")
        em_payload["n_scored_rows"] = stack.get("n_scored_rows")
        em_payload["dates_used"] = stack.get("dates_used")
        summ = stack.get("superiority_summary") or {}
        em_payload["required_stats_missing_in_event_rows"] = summ.get("required_stats_missing_in_event_rows")
        em_payload["eligible_market_subset_superiority_claim_allowed"] = summ.get(
            "eligible_market_subset_superiority_claim_allowed", False
        )
        em_payload["model_only_calibration_claim_allowed"] = summ.get(
            "model_only_calibration_claim_allowed", False
        )
        n_scored = int(stack.get("n_scored_rows") or 0)
        if n_scored <= 0:
            em_payload["market_eval_status"] = "blocked_insufficient_scored_rows"
            logger.error("PHASE8_MARKET_EVAL_NOT_WIRED_FAIL: n_scored_rows==0")
            sys.exit(2)
        em_payload["market_eval_status"] = "event_market_scored"
        strict_rc = int(stack.get("strict_verifier_exit_code") or 1)
        prov_rc = stack.get("provisional_verifier_exit_code")
        if strict_rc == 0:
            em_payload["strict_contract_result"] = "pass"
        elif prov_rc is not None and int(prov_rc) == 0:
            em_payload["strict_contract_result"] = "blocked_provisional"
        else:
            em_payload["strict_contract_result"] = "fail"

        summ_global_raw = bool(summ.get("global_market_superiority_claim_allowed", False))
        eligible_raw = bool(summ.get("eligible_market_subset_superiority_claim_allowed", False))
        strict_pass = em_payload["strict_contract_result"] == "pass"
        em_payload["global_market_superiority_claim_allowed"] = summ_global_raw and strict_pass
        em_payload["eligible_market_subset_superiority_claim_allowed"] = eligible_raw
        em_payload["market_superiority_claim_allowed"] = bool(
            em_payload["global_market_superiority_claim_allowed"]
        )
        scr = em_payload["strict_contract_result"]
        if scr == "pass":
            em_payload["promotion_status"] = (
                "market_superiority_verified"
                if em_payload["global_market_superiority_claim_allowed"]
                else "no_market_superiority_claim"
            )
        elif scr == "blocked_provisional":
            em_payload["promotion_status"] = "MARKET_SUPERIORITY_CONTRACT_BLOCKED"
        else:
            em_payload["promotion_status"] = "no_market_superiority_claim"

    elif args.allow_baseline_only:
        em_payload["market_eval_status"] = "baseline_only"

    if args.require_market_eval and em_payload.get("market_eval_status") == "event_market_scored":
        _append_event_market_diag_section(report_path, em_payload)

    # Sidecar JSON for downstream consumers (WoO / EV Analytics).
    sidecar = DOCS_DIR / f"diagnostics_{args.run_date}.meta.json"
    sidecar.write_text(
        json.dumps(
            {
                "market_eval_oof_opening_lines_available": bool(
                    MARKET_EVAL_OOF_OPENING_LINES_AVAILABLE
                ),
                "lift_baseline": (
                    "neutral_0p5"
                    if not MARKET_EVAL_OOF_OPENING_LINES_AVAILABLE
                    else "devigged_opening_line"
                ),
                "run_date": args.run_date,
                "training_table": str(Path(args.training_table).resolve()),
                "require_market_eval": bool(args.require_market_eval),
                "allow_baseline_only": bool(args.allow_baseline_only),
                **em_payload,
            },
            indent=2,
            allow_nan=False,
        )
        + "\n",
    )

    logger.info(f"Wrote {report_path}")
    logger.info(f"Done in {(time.time() - start):.1f}s")


# ── helpers ─────────────────────────────────────────────────────────────────


def _pad_or_truncate_pmf(pmfs: np.ndarray, target_len: int) -> np.ndarray:
    if pmfs.shape[1] == target_len:
        return pmfs
    if pmfs.shape[1] > target_len:
        out = pmfs[:, :target_len].copy()
        out[:, -1] += pmfs[:, target_len:].sum(axis=1)
        out = out / np.clip(out.sum(axis=1, keepdims=True), 1e-9, None)
        return out
    out = np.zeros((len(pmfs), target_len))
    out[:, :pmfs.shape[1]] = pmfs
    return out


def _cdf_at(pmfs: np.ndarray, x: float) -> np.ndarray:
    """P(stat <= x) for an integer-valued stat PMF (discrete step CDF).

    Mirrors the production fix from Stage 1 (StatPMF.cdf in
    src/nba_props_model/models/simulation.py): the CDF jumps at each
    integer atom and is constant between atoms. The previous
    interpolation form was incorrect for integer outcomes and
    distorted over/under probabilities at half-point reference lines.
    """
    cdfs = np.cumsum(pmfs, axis=1)
    cdfs = np.clip(cdfs, 0.0, 1.0)
    if x < 0:
        return np.zeros(len(pmfs))
    k = int(np.floor(x))
    if k >= cdfs.shape[1] - 1:
        return np.ones(len(pmfs))
    return cdfs[:, k]


def _fold_metrics_from(
    pmfs: np.ndarray, outcomes: np.ndarray,
    over_probs_model: np.ndarray, over_probs_market: np.ndarray,
    over_realised: np.ndarray, stat: str, fold_start: str, fold_end: str,
    rng: np.random.Generator,
) -> FoldMetrics:
    pit = randomized_pit(pmfs, outcomes, rng)
    ks = pit_ks_distance(pit)
    bs = brier(over_probs_model, over_realised)
    ece_v = ece(over_probs_model, over_realised)
    fit = calibration_line_fit(over_probs_model, over_realised)
    slope = float(fit["slope"]) if fit["slope"] is not None else float("nan")
    intercept = float(fit["intercept"]) if fit["intercept"] is not None else float("nan")
    ls = log_score(pmfs, outcomes)
    crps = discrete_crps(pmfs, outcomes)
    # If market probabilities are NaN (the unavailable path), emit
    # market_logscore_lift = NaN rather than computing a misleading
    # constant-0.5 baseline lift.
    if not np.all(np.isfinite(over_probs_market)):
        return FoldMetrics(
            fold_start=fold_start, fold_end=fold_end, stat=stat, n=int(len(outcomes)),
            log_score=ls, crps=crps,
            pit_mean=float(np.mean(pit)), pit_std=float(np.std(pit)), pit_ks=ks,
            brier=bs, ece=ece_v,
            cal_slope=slope, cal_intercept=intercept,
            market_logscore_lift=float("nan"),
            edge_monotonicity_rho=float("nan"),
            cal_slope_status=str(fit["calibration_slope_status"]),
            cal_slope_valid=bool(fit["calibration_slope_valid"]),
            constant_prob_n=fit["constant_prob_n"],
            constant_prob_value=fit["constant_prob_value"],
        )
    market_logscore = -np.mean(
        over_realised * np.log(np.clip(over_probs_market, 1e-9, 1 - 1e-9))
        + (1 - over_realised) * np.log(np.clip(1 - over_probs_market, 1e-9, 1 - 1e-9))
    )
    model_logscore = -np.mean(
        over_realised * np.log(np.clip(over_probs_model, 1e-9, 1 - 1e-9))
        + (1 - over_realised) * np.log(np.clip(1 - over_probs_model, 1e-9, 1 - 1e-9))
    )
    lift = float(market_logscore - model_logscore)
    return FoldMetrics(
        fold_start=fold_start, fold_end=fold_end, stat=stat, n=int(len(outcomes)),
        log_score=ls, crps=crps,
        pit_mean=float(np.mean(pit)), pit_std=float(np.std(pit)), pit_ks=ks,
        brier=bs, ece=ece_v,
        cal_slope=slope, cal_intercept=intercept,
        market_logscore_lift=lift,
        edge_monotonicity_rho=float("nan"),
        cal_slope_status=str(fit["calibration_slope_status"]),
        cal_slope_valid=bool(fit["calibration_slope_valid"]),
        constant_prob_n=fit["constant_prob_n"],
        constant_prob_value=fit["constant_prob_value"],
    )


def _build_legacy_pmfs_for_rows(
    stat: str, chunk: pd.DataFrame, training_df: pd.DataFrame,
    legacy_features: list[str], legacy_ladder: dict[int, object],
    domain_max: int,
) -> Optional[np.ndarray]:
    """Reconstruct per-row legacy PMFs using the saved quantile ladder."""
    # Match chunk rows to training_df by (player_id, game_id, stat).
    stat_training = training_df[training_df["stat"] == stat]
    lookup = stat_training.set_index(["player_id", "game_id"])
    pmfs = []
    for r in chunk.itertuples(index=False):
        key = (int(r.player_id), int(r.game_id))
        if key not in lookup.index:
            pmfs.append(np.zeros(domain_max + 1))
            continue
        row = lookup.loc[key]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]
        feat_vec = pd.DataFrame([
            {f: float(row.get(f, 0.0) or 0.0) for f in legacy_features}
        ])
        q_preds: dict[int, float] = {}
        for qpct, m in legacy_ladder.items():
            try:
                q_preds[qpct] = float(m.predict(feat_vec)[0])
            except Exception:
                continue
        pmfs.append(legacy_pmf_from_quantiles(stat, q_preds, domain_max))
    return np.stack(pmfs) if pmfs else None


def _append_comparison_summary(
    path: Path, fold_metrics: list[FoldMetrics], run_date: str,
) -> None:
    by_stat_path: dict[str, dict[str, list[FoldMetrics]]] = {}
    for m in fold_metrics:
        if "__" not in m.stat:
            continue
        base, path_tag = m.stat.split("__")
        by_stat_path.setdefault(base, {"new": [], "legacy": []})
        by_stat_path[base].setdefault(path_tag, []).append(m)

    lines = [
        "",
        "---",
        "",
        "## New PMF path vs legacy direct-total path — aggregate",
        "",
        "| stat | metric | legacy | new | better |",
        "|---|---|---:|---:|---|",
    ]
    verdict: dict[str, dict[str, str]] = {}
    for stat in sorted(by_stat_path.keys()):
        v = {}
        for metric, lower_better in [
            ("log_score", True), ("crps", True), ("pit_ks", True),
            ("brier", True), ("ece", True),
        ]:
            legacy_vals = [getattr(m, metric) for m in by_stat_path[stat].get("legacy", [])
                           if np.isfinite(getattr(m, metric))]
            new_vals = [getattr(m, metric) for m in by_stat_path[stat].get("new", [])
                        if np.isfinite(getattr(m, metric))]
            if not legacy_vals or not new_vals:
                continue
            lmean = float(np.mean(legacy_vals))
            nmean = float(np.mean(new_vals))
            if lower_better:
                better = "new" if nmean < lmean else "legacy" if nmean > lmean else "tie"
            else:
                better = "new" if nmean > lmean else "legacy" if nmean < lmean else "tie"
            v[metric] = better
            lines.append(
                f"| {stat} | {metric} | {lmean:.4f} | {nmean:.4f} | {better} |"
            )
        verdict[stat] = v
    lines.append("")
    lines.append("## Per-stat verdict")
    lines.append("")
    for stat, v in verdict.items():
        wins = sum(1 for b in v.values() if b == "new")
        losses = sum(1 for b in v.values() if b == "legacy")
        ties = sum(1 for b in v.values() if b == "tie")
        note = (
            "new path passes" if wins >= losses
            else "LEGACY still wins on this stat; do not activate bet selection yet"
        )
        lines.append(f"- **{stat}**: new wins {wins} / legacy wins {losses} / ties {ties}. {note}")
    existing = path.read_text() if path.exists() else ""
    path.write_text(existing + "\n".join(lines) + "\n")


def _append_role_stratified_section(
    path: Path, role_rows: list[dict],
) -> None:
    """Append role-stratified PMF diagnostics to the report.

    No-op when role_rows is empty (older OOF parquets without
    role_bucket simply produce no rows in the upstream loop).
    """
    if not role_rows:
        return
    buckets_seen = sorted({r["role_bucket"] for r in role_rows})
    total_n = sum(int(r["n"]) for r in role_rows)
    lines = [
        "",
        "---",
        "",
        "## Role-aware PMF diagnostics by stat × role_bucket",
        "",
        "_Diagnostics use active-conditioned PMFs (`pmf_active`) when "
        "the OOF parquet carries that column; otherwise fall back to "
        "raw `pmf`. Calibrators are fit on the same source._",
        "",
        f"Evaluated role buckets: {', '.join(buckets_seen)}; rows: {total_n:,}",
        "",
        "| stat | role_bucket | n | log_score | CRPS | PIT mean | PIT std | PIT KS | ECE |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in sorted(role_rows, key=lambda x: (x["stat"], x["role_bucket"])):
        lines.append(
            f"| {r['stat']} | {r['role_bucket']} | {r['n']} | "
            f"{r['log_score']:.4f} | {r['crps']:.4f} | "
            f"{r['pit_mean']:.4f} | {r['pit_std']:.4f} | {r['pit_ks']:.4f} | "
            f"{r['ece']:.4f} |"
        )
    existing = path.read_text() if path.exists() else ""
    path.write_text(existing + "\n".join(lines) + "\n")


def _append_event_market_diag_section(path: Path, em: dict) -> None:
    lines = [
        "",
        "---",
        "",
        "## M8.6 event-market validation (Odds API → processed odds → loss rows)",
        "",
        f"- `market_eval_status`: **{em.get('market_eval_status')}**",
        f"- `strict_contract_result`: **{em.get('strict_contract_result')}**",
        f"- `n_event_market_rows`: {em.get('n_event_market_rows')}",
        f"- `n_matched_rows`: {em.get('n_matched_rows')}",
        f"- `n_scored_rows`: {em.get('n_scored_rows')}",
        f"- `dates_used`: {em.get('dates_used')}",
        f"- `global_market_superiority_claim_allowed`: {em.get('global_market_superiority_claim_allowed')}",
        f"- `eligible_market_subset_superiority_claim_allowed`: "
        f"{em.get('eligible_market_subset_superiority_claim_allowed')}",
        f"- `model_only_calibration_claim_allowed`: {em.get('model_only_calibration_claim_allowed')}",
        "",
    ]
    existing = path.read_text() if path.exists() else ""
    path.write_text(existing + "\n".join(lines) + "\n")


def _append_market_eval_status(path: Path, available: bool) -> None:
    """Append an explicit 'Market evaluation status' section to the
    diagnostics markdown so consumers can never mistake a
    neutral-0.5 baseline lift for a real market-relative comparison.
    Always emitted — never silent — even when available=True (in
    which case it states which baseline was used)."""
    lines = [
        "",
        "---",
        "",
        "## Market evaluation status",
        "",
    ]
    if not available:
        lines += [
            "**Market-relative evaluation unavailable: no matched de-vigged "
            "market probabilities found.**",
            "",
            "The `logloss lift` column in the per-stat tables above is emitted "
            "as `nan` because real opening-line de-vigged over/under "
            "probabilities are not currently joined onto the OOF rows. The "
            "previous code path silently substituted a constant 0.5 baseline, "
            "which produced a misleading non-zero lift. This report now flags "
            "the gap explicitly.",
            "",
            "`market_eval_available = false`",
            "",
            "Wiring real market data requires joining `data/opening_lines_*.json` "
            "to the OOF parquet by `(player_name, game_date, stat, line)`; "
            "the helpers `devigged_main_line` / "
            "`market_implied_cdf_from_alt_lines` in "
            "`src/nba_props_model/evaluation/market_baseline.py` are ready to "
            "consume that join.",
        ]
    else:
        lines += [
            "Market-relative evaluation enabled. `logloss lift` column above "
            "is computed against per-row de-vigged opening-line probabilities.",
            "",
            "`market_eval_available = true`",
        ]
    existing = path.read_text() if path.exists() else ""
    path.write_text(existing + "\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
