"""
Run the full-universe diagnostics suite comparing the new PMF path
against the legacy direct-total path on the same walk-forward holdout.

Per docs/MIGRATION.md §3 step 4: writes
artifacts/docs/diagnostics_{today}.md with per-stat metrics.

Metrics per stat and per fold:
  * log score on the realized outcome under the predicted PMF
  * discrete CRPS
  * randomized PIT mean / std / KS distance from Uniform(0,1)
  * line-level Brier averaged over offered lines from opening-snapshot
  * over/under calibration: slope, intercept, ECE
  * market-relative log-score lift vs the de-vigged opening market probs
  * edge-decile monotonicity where enough graded rows exist
  * bootstrap ROI 95% CI on the selected-bet subset

Comparison baseline: the *legacy* direct-total quantile path reads
the `q{qpct}_{stat}.pkl` artifacts in artifacts/models/. The new path
reads the same validation rows' PMFs generated by
scripts/calibrate_pmf.py's OOF sweep.
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import joblib  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from nba_props_model.calibration.pmf_calibration import load_calibrator  # noqa: E402
from nba_props_model.evaluation.diagnostics import (  # noqa: E402
    FoldMetrics, american_to_implied_prob, bootstrap_ci,
    brier, calibration_slope_intercept, devig_pair,
    discrete_crps, ece, edge_decile_monotonicity, log_score,
    pit_ks_distance, randomized_pit, write_report,
)
from nba_props_model.paths import DATA_DIR, MODEL_DIR, REPO_ROOT  # noqa: E402
from nba_props_model.models.simulation import DOMAIN_MAX as MAIN_DOMAIN_MAX  # noqa: E402
from nba_props_model.models.sparse_hurdle import DOMAIN_MAX as SPARSE_DOMAIN_MAX  # noqa: E402

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("run_diagnostics")


DOCS_DIR = REPO_ROOT / "artifacts" / "docs"


# ── legacy PMF construction from quantile ladder ───────────────────────────


LEGACY_QUANTILES = (0.10, 0.20, 0.25, 0.33, 0.40, 0.50, 0.60, 0.67, 0.75, 0.80, 0.90)


def legacy_pmf_from_quantiles(
    stat: str, quantile_predictions: dict[int, float], domain_max: int,
) -> np.ndarray:
    """Approximate the legacy direct-total path's discrete PMF from its
    quantile ladder at the offered tau values. We anchor at (0, 0) and
    (domain_max, 1) and use linear CDF interpolation."""
    if not quantile_predictions:
        # Degenerate: uniform over the support.
        pmf = np.ones(domain_max + 1) / (domain_max + 1)
        return pmf
    sorted_keys = sorted(quantile_predictions.keys())
    xs = [max(0.0, float(quantile_predictions[k])) for k in sorted_keys]
    for i in range(1, len(xs)):
        if xs[i] < xs[i - 1]:
            xs[i] = xs[i - 1]
    ys = [k / 100.0 for k in sorted_keys]
    xs = [0.0] + xs + [float(domain_max) + 1e-6]
    ys = [0.0] + ys + [1.0]
    support = np.arange(domain_max + 1, dtype=float)
    cdf = np.interp(support, xs, ys)
    cdf[-1] = 1.0
    pmf = np.empty_like(cdf)
    pmf[0] = cdf[0]
    pmf[1:] = np.diff(cdf)
    pmf = np.clip(pmf, 0.0, None)
    s = pmf.sum()
    if s > 0:
        pmf = pmf / s
    return pmf


def load_legacy_ladder(stat: str) -> tuple[Optional[list[str]], dict[int, object]]:
    feat_path = MODEL_DIR / f"features_{stat}.pkl"
    if not feat_path.exists():
        return None, {}
    try:
        features = joblib.load(feat_path)
    except Exception:
        return None, {}
    ladder: dict[int, object] = {}
    for q in LEGACY_QUANTILES:
        qpct = int(round(q * 100))
        p = MODEL_DIR / f"q{qpct:02d}_{stat}.pkl"
        if p.exists():
            try:
                ladder[qpct] = joblib.load(p)
            except Exception:
                continue
    return features, ladder


# ── per-stat diagnostic collector ──────────────────────────────────────────


STATS_TO_REPORT = ["pts", "reb", "ast", "tov", "stl", "blk", "fg3m", "stocks"]

DOMAIN_FOR_STAT = {
    **{s: MAIN_DOMAIN_MAX[s] for s in ("pts", "reb", "ast", "tov")},
    **{s: SPARSE_DOMAIN_MAX[s] for s in ("stl", "blk")},
    "stocks": SPARSE_DOMAIN_MAX["stl"] + SPARSE_DOMAIN_MAX["blk"],
    "fg3m": 15,
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--oof-path", default=str(DATA_DIR / "oof_pmfs.parquet"),
        help="Path to the OOF PMF parquet produced by calibrate_pmf.",
    )
    parser.add_argument("--run-date", default=datetime.utcnow().strftime("%Y-%m-%d"))
    args = parser.parse_args()

    start = time.time()
    logger.info("=" * 60)
    logger.info("Diagnostics — legacy direct-total vs new PMF path")
    logger.info("=" * 60)

    oof_path = Path(args.oof_path)
    if not oof_path.exists():
        logger.error(
            f"No OOF file at {oof_path}. Run scripts/calibrate_pmf.py "
            "with --emit-oof (or the default behavior that writes it) first."
        )
        sys.exit(1)

    stats_df = pd.read_parquet(DATA_DIR / "player_game_stats.parquet")
    training_df = pd.read_parquet(DATA_DIR / "training_table.parquet")
    training_df["game_date"] = training_df["game_date"].astype(str).str[:10]

    oof = pd.read_parquet(oof_path)
    oof["game_date"] = oof["game_date"].astype(str).str[:10]

    fold_metrics: list[FoldMetrics] = []
    new_rows: list[dict] = []
    legacy_rows: list[dict] = []

    rng = np.random.default_rng(0)
    for stat in sorted(oof["stat"].unique()):
        sub = oof[oof["stat"] == stat].copy()
        sub = sub.sort_values("game_date")
        if len(sub) < 80:
            logger.warning(f"  {stat}: only {len(sub)} OOF rows — skipping diagnostics")
            continue
        domain_max = DOMAIN_FOR_STAT.get(stat, sub["pmf"].iloc[0].shape[0] - 1)

        new_pmfs = np.stack(sub["pmf"].values)
        new_pmfs = _pad_or_truncate_pmf(new_pmfs, domain_max + 1)
        outcomes = sub["outcome"].values.astype(int)

        # Evaluate new PMF diagnostics fold by fold.
        sub["fold"] = sub["fold_start"].astype(str)
        for fstart in sorted(sub["fold"].unique()):
            chunk = sub[sub["fold"] == fstart]
            if len(chunk) < 50:
                continue
            idx = chunk.index
            sub_idx = [sub.index.get_loc(i) for i in idx]
            pmf_slice = new_pmfs[sub_idx]
            out_slice = outcomes[sub_idx]

            # Calibrated PMF if available.
            cal = load_calibrator(stat)
            if cal is not None:
                pmf_slice_cal = np.stack([cal.apply(p) for p in pmf_slice])
            else:
                pmf_slice_cal = pmf_slice

            # Over-prob model: prob(stat > nearest integer line) at a reference
            # line equal to the per-fold median integer for this stat.
            ref_line = float(np.median(out_slice)) + 0.5
            over_probs = 1.0 - _cdf_at(pmf_slice_cal, ref_line)
            over_realised = (out_slice > ref_line).astype(int)

            market_probs = np.full(len(over_realised), 0.5)

            fm_new = _fold_metrics_from(
                pmf_slice_cal, out_slice, over_probs, market_probs,
                over_realised, stat=f"{stat}__new",
                fold_start=str(chunk["fold_start"].iloc[0]),
                fold_end=str(chunk["fold_end"].iloc[0]),
                rng=rng,
            )
            fold_metrics.append(fm_new)

            # Now the legacy direct-total path on the same rows.
            legacy_features, legacy_ladder = load_legacy_ladder(stat if stat != "tov" else "tov")
            if legacy_features and legacy_ladder:
                legacy_pmfs = _build_legacy_pmfs_for_rows(
                    stat, chunk, training_df, legacy_features, legacy_ladder,
                    domain_max=domain_max,
                )
                if legacy_pmfs is not None and len(legacy_pmfs) == len(out_slice):
                    over_probs_legacy = 1.0 - _cdf_at(legacy_pmfs, ref_line)
                    fm_legacy = _fold_metrics_from(
                        legacy_pmfs, out_slice, over_probs_legacy,
                        market_probs, over_realised, stat=f"{stat}__legacy",
                        fold_start=str(chunk["fold_start"].iloc[0]),
                        fold_end=str(chunk["fold_end"].iloc[0]),
                        rng=rng,
                    )
                    fold_metrics.append(fm_legacy)
                    legacy_rows.extend(
                        [{"stat": stat, "pmf": p, "outcome": y, "fold_start": chunk["fold_start"].iloc[0]}
                         for p, y in zip(legacy_pmfs, out_slice)]
                    )
            new_rows.extend(
                [{"stat": stat, "pmf": p, "outcome": y, "fold_start": chunk["fold_start"].iloc[0]}
                 for p, y in zip(pmf_slice_cal, out_slice)]
            )

    report_path = DOCS_DIR / f"diagnostics_{args.run_date}.md"
    write_report(fold_metrics, run_date=args.run_date)
    # Append cross-path comparison summary.
    _append_comparison_summary(report_path, fold_metrics, args.run_date)

    logger.info(f"Wrote {report_path}")
    logger.info(f"Done in {(time.time() - start):.1f}s")


# ── helpers ─────────────────────────────────────────────────────────────────


def _pad_or_truncate_pmf(pmfs: np.ndarray, target_len: int) -> np.ndarray:
    if pmfs.shape[1] == target_len:
        return pmfs
    if pmfs.shape[1] > target_len:
        out = pmfs[:, :target_len].copy()
        out[:, -1] += pmfs[:, target_len:].sum(axis=1)
        out = out / np.clip(out.sum(axis=1, keepdims=True), 1e-9, None)
        return out
    out = np.zeros((len(pmfs), target_len))
    out[:, :pmfs.shape[1]] = pmfs
    return out


def _cdf_at(pmfs: np.ndarray, x: float) -> np.ndarray:
    cdfs = np.cumsum(pmfs, axis=1)
    cdfs = np.clip(cdfs, 0.0, 1.0)
    if x < 0:
        return np.zeros(len(pmfs))
    if x >= cdfs.shape[1] - 1:
        return np.ones(len(pmfs))
    lo = int(np.floor(x))
    hi = lo + 1
    w = x - lo
    return (1 - w) * cdfs[:, lo] + w * cdfs[:, min(hi, cdfs.shape[1] - 1)]


def _fold_metrics_from(
    pmfs: np.ndarray, outcomes: np.ndarray,
    over_probs_model: np.ndarray, over_probs_market: np.ndarray,
    over_realised: np.ndarray, stat: str, fold_start: str, fold_end: str,
    rng: np.random.Generator,
) -> FoldMetrics:
    pit = randomized_pit(pmfs, outcomes, rng)
    ks = pit_ks_distance(pit)
    bs = brier(over_probs_model, over_realised)
    ece_v = ece(over_probs_model, over_realised)
    slope, intercept = calibration_slope_intercept(over_probs_model, over_realised)
    ls = log_score(pmfs, outcomes)
    crps = discrete_crps(pmfs, outcomes)
    market_logscore = -np.mean(
        over_realised * np.log(np.clip(over_probs_market, 1e-9, 1 - 1e-9))
        + (1 - over_realised) * np.log(np.clip(1 - over_probs_market, 1e-9, 1 - 1e-9))
    )
    model_logscore = -np.mean(
        over_realised * np.log(np.clip(over_probs_model, 1e-9, 1 - 1e-9))
        + (1 - over_realised) * np.log(np.clip(1 - over_probs_model, 1e-9, 1 - 1e-9))
    )
    lift = float(market_logscore - model_logscore)
    return FoldMetrics(
        fold_start=fold_start, fold_end=fold_end, stat=stat, n=int(len(outcomes)),
        log_score=ls, crps=crps,
        pit_mean=float(np.mean(pit)), pit_std=float(np.std(pit)), pit_ks=ks,
        brier=bs, ece=ece_v,
        cal_slope=slope, cal_intercept=intercept,
        market_logscore_lift=lift,
        edge_monotonicity_rho=float("nan"),
    )


def _build_legacy_pmfs_for_rows(
    stat: str, chunk: pd.DataFrame, training_df: pd.DataFrame,
    legacy_features: list[str], legacy_ladder: dict[int, object],
    domain_max: int,
) -> Optional[np.ndarray]:
    """Reconstruct per-row legacy PMFs using the saved quantile ladder."""
    # Match chunk rows to training_df by (player_id, game_id, stat).
    stat_training = training_df[training_df["stat"] == stat]
    lookup = stat_training.set_index(["player_id", "game_id"])
    pmfs = []
    for r in chunk.itertuples(index=False):
        key = (int(r.player_id), int(r.game_id))
        if key not in lookup.index:
            pmfs.append(np.zeros(domain_max + 1))
            continue
        row = lookup.loc[key]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]
        feat_vec = pd.DataFrame([
            {f: float(row.get(f, 0.0) or 0.0) for f in legacy_features}
        ])
        q_preds: dict[int, float] = {}
        for qpct, m in legacy_ladder.items():
            try:
                q_preds[qpct] = float(m.predict(feat_vec)[0])
            except Exception:
                continue
        pmfs.append(legacy_pmf_from_quantiles(stat, q_preds, domain_max))
    return np.stack(pmfs) if pmfs else None


def _append_comparison_summary(
    path: Path, fold_metrics: list[FoldMetrics], run_date: str,
) -> None:
    by_stat_path: dict[str, dict[str, list[FoldMetrics]]] = {}
    for m in fold_metrics:
        if "__" not in m.stat:
            continue
        base, path_tag = m.stat.split("__")
        by_stat_path.setdefault(base, {"new": [], "legacy": []})
        by_stat_path[base].setdefault(path_tag, []).append(m)

    lines = [
        "",
        "---",
        "",
        "## New PMF path vs legacy direct-total path — aggregate",
        "",
        "| stat | metric | legacy | new | better |",
        "|---|---|---:|---:|---|",
    ]
    verdict: dict[str, dict[str, str]] = {}
    for stat in sorted(by_stat_path.keys()):
        v = {}
        for metric, lower_better in [
            ("log_score", True), ("crps", True), ("pit_ks", True),
            ("brier", True), ("ece", True),
        ]:
            legacy_vals = [getattr(m, metric) for m in by_stat_path[stat].get("legacy", [])
                           if np.isfinite(getattr(m, metric))]
            new_vals = [getattr(m, metric) for m in by_stat_path[stat].get("new", [])
                        if np.isfinite(getattr(m, metric))]
            if not legacy_vals or not new_vals:
                continue
            lmean = float(np.mean(legacy_vals))
            nmean = float(np.mean(new_vals))
            if lower_better:
                better = "new" if nmean < lmean else "legacy" if nmean > lmean else "tie"
            else:
                better = "new" if nmean > lmean else "legacy" if nmean < lmean else "tie"
            v[metric] = better
            lines.append(
                f"| {stat} | {metric} | {lmean:.4f} | {nmean:.4f} | {better} |"
            )
        verdict[stat] = v
    lines.append("")
    lines.append("## Per-stat verdict")
    lines.append("")
    for stat, v in verdict.items():
        wins = sum(1 for b in v.values() if b == "new")
        losses = sum(1 for b in v.values() if b == "legacy")
        ties = sum(1 for b in v.values() if b == "tie")
        note = (
            "new path passes" if wins >= losses
            else "LEGACY still wins on this stat; do not activate bet selection yet"
        )
        lines.append(f"- **{stat}**: new wins {wins} / legacy wins {losses} / ties {ties}. {note}")
    existing = path.read_text() if path.exists() else ""
    path.write_text(existing + "\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
